# Site settings
author: Alex L
title: Alex does [CODE]
header-img: img/home-bg.png
email: hyunho98@gmail.com
copyright_name: Alex L
description: > # this means to ignore newlines until "baseurl:"
  10 months of learn.co
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hyunho98

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
